from pathlib import Path
from typing import List, Optional, Tuple

from pathspec import PathSpec

from .ignorer import PILIGNOR_FILENAME, is_ignored, load_spec

LARGE_FILE_THRESHOLD = 100 * 1024  # 100 KB

SAFE_SECTIONS: List[Tuple[str, List[str]]] = [
    ("Environments", ["venv/", ".venv/", "env/", "ENV/"]),
    ("Python caches", ["__pycache__/", "*.py[cod]", "*.pyo"]),
    ("Tool caches", [".pytest_cache/", ".mypy_cache/", ".ruff_cache/", ".cache/"]),
    ("Build artifacts", ["build/", "dist/", "*.egg-info/", "*.egg"]),
    ("IDE / editors", [".idea/", ".vscode/", ".gigacode_vsc/"]),
    ("Secrets", [".env", "*.pem", "*.key"]),
    ("Logs", ["*.log"]),
    ("Coverage", [".coverage", "htmlcov/", "coverage/"]),
]

AGGRESSIVE_SECTIONS: List[Tuple[str, List[str]]] = [
    ("Assets", ["static/", "media/"]),
    ("Dumps / reports", ["*_dump.md", "report.txt"]),
]


def find_large_files(
    root_path: Path,
    threshold: int = LARGE_FILE_THRESHOLD,
    spec: Optional[PathSpec] = None,
) -> List[str]:
    """Return relative posix paths of files larger than ``threshold`` bytes.

    Files already matched by ``spec`` (e.g. .gitignore / .pilignor rules) are
    skipped, so generated hints never leak paths from virtualenvs or caches.
    """
    large: List[str] = []
    for item in root_path.rglob("*"):
        if any(part == ".git" for part in item.parts):
            continue
        if item.is_symlink():
            continue
        if not item.is_file():
            continue
        if spec is not None and is_ignored(item, root_path, spec):
            continue
        try:
            if item.stat().st_size > threshold:
                large.append(item.relative_to(root_path).as_posix())
        except OSError:
            continue
    return sorted(large)


def generate_ignore_content(root_path: Path, mode: str = "safe") -> str:
    """Build the content of a starter .pilignor file.

    ``mode='safe'`` includes only obvious junk; ``mode='aggressive'`` also
    enables asset/dump patterns and lists large files.
    """
    lines: List[str] = [
        f"# {PILIGNOR_FILENAME} - extra files excluded from AI packing.",
        "# Applied on top of .gitignore. One pattern per line (gitignore syntax).",
        "# Prefix a pattern with '!' to re-include it.",
        "# Generated by: pilepack --init-ignore",
        "",
    ]

    for title, patterns in SAFE_SECTIONS:
        lines.append(f"# {title}")
        lines.extend(patterns)
        lines.append("")

    aggressive = mode == "aggressive"
    for title, patterns in AGGRESSIVE_SECTIONS:
        if aggressive:
            lines.append(f"# {title}")
            lines.extend(patterns)
        else:
            lines.append(f"# {title} (uncomment to exclude)")
            lines.extend(f"# {pattern}" for pattern in patterns)
        lines.append("")

    if aggressive:
        large_files = find_large_files(root_path, spec=load_spec(root_path))
        if large_files:
            lines.append(f"# Large files (> {LARGE_FILE_THRESHOLD // 1024} KB)")
            lines.extend(large_files)
            lines.append("")

    return "\n".join(lines) + "\n"
